services:
  blogapi2:
    image: ${DOCKER_REGISTRY-}blogapi
    container_name: blogapi
    build:
      context: .
      dockerfile: BlogAPI2/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"

  database:
    image: postgres:latest
    container_name: database
    environment:
        - POSTGRES_DB=blogs
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
    volumes:
        - ./.containers/blogs-db:/var/lib/postgresql/data
    ports:
        - 5432:5432    