version: '3.8'

services:
  blogdb:
    image: mongo
    container_name: blogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      #MONGO_INITDB_ROOT_USERNAME: xxx
      #MONGO_INITDB_ROOT_PASSWORD: xxx
      MONGO_INITDB_DATABASE: blogs
    command: mongod --port 27017
    #networks:
    #  - net7-network

  blogapi:
    container_name: blogapi
    restart: always
    build:
      context: .
      dockerfile: BlogApi2/Dockerfile
    depends_on:
      - blogdb
    ports:
      - "8000:80"
    #networks:
    #  - net7-network

volumes:
  mongo_data:

#networks:
#  net7-network:
#    driver: bridge